apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage
  namespace: mariadb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi  # Adjust the storage size as needed